#!/usr/bin/env python3
"""Flatten aliases + titles across health-papers/*.md into _data/topics.yml.

Phase 4 of .ai/plans/topic-taxonomy.md. Grouping/deduping terms case-
insensitively across ~180 pages isn't practical in pure Liquid, so this
script does it once and commits the result as data; health-papers/topics/
renders it with plain Liquid (group_by_exp, no plugins). Idempotent: re-run
whenever a paper's aliases or title change.
"""
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
PAPERS_DIR = REPO_ROOT / "health-papers"
OUT_PATH = REPO_ROOT / "_data" / "topics.yml"

FRONT_MATTER_RE = re.compile(r"\A---\s*\n(.*?\n)---\s*\n", re.DOTALL)


def load_papers():
    papers = []
    for path in sorted(PAPERS_DIR.glob("*.md")):
        if path.name == "index.md":
            continue
        match = FRONT_MATTER_RE.match(path.read_text())
        if not match:
            continue
        front_matter = yaml.safe_load(match.group(1)) or {}
        if front_matter.get("exclude_from_papers"):
            continue
        title = front_matter.get("title")
        permalink = front_matter.get("permalink")
        if not title or not permalink:
            continue
        aliases = front_matter.get("aliases") or []
        papers.append({"title": title, "url": permalink, "aliases": aliases})
    return papers


def build_terms(papers):
    # key: lowercased term -> {"term": display form, "entries": [{"title","url"}]}
    terms = {}
    for paper in papers:
        candidates = [paper["title"]] + list(paper["aliases"])
        for term in candidates:
            term = term.strip()
            if not term:
                continue
            key = term.lower()
            bucket = terms.setdefault(key, {"term": term, "entries": []})
            entry = {"title": paper["title"], "url": paper["url"]}
            if entry not in bucket["entries"]:
                bucket["entries"].append(entry)
    return terms


def main():
    papers = load_papers()
    terms = build_terms(papers)

    topics = []
    for bucket in terms.values():
        entries = sorted(bucket["entries"], key=lambda e: e["title"])
        topics.append({"term": bucket["term"], "papers": entries})
    topics.sort(key=lambda t: t["term"].lower())

    header = (
        "# Generated by .ai/scripts/generate-topics-data.py — do not hand-edit.\n"
        "# Flattened, deduped index of paper titles + aliases -> paper(s).\n"
        "# Re-run the script after changing any paper's title/aliases.\n\n"
    )
    OUT_PATH.write_text(header + yaml.safe_dump(topics, allow_unicode=True, sort_keys=False))
    print(f"wrote {len(topics)} topic entries from {len(papers)} papers to {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
